
liquibase:
  target: ./data/out.xml
  output: ./data/newfile.xml
  changesetId: 
  
jpaentity:
  selector:
    lowercase: true
    include:
    - tr_.*
    - ts_.*
    exclude:
    - ts_svc_cust_m_aud
  database:
    jdbcDriver: org.h2.Driver
    url: jdbc:h2:file:~/h2db/smp/smp;DB_CLOSE_DELAY=-1
    username: smp
    password:
  entity:
    hasSuper: true
    prefix: Super
    writepath: ./data/out
    entPackage: onlyone.smp.persistent.domain.rdbms
    keyPackage: onlyone.smp.persistent.domain.keys
    superPackage: onlyone.smp.persistent.domain.mapsuper
  changetype:
    typechange:
    -
      before: TIMESTAMP
      after: java.time.LocalDateTime
    enumchange:
    -
      before: BROK_STS_CD
      after: onlyone.smp.persistent.domain.enums.EBrokSts
    